// ── Flashcard Types & Static Data ──────────────────────────

export interface Flashcard {
  id: string
  front: string
  back: string
  section: 'quant' | 'verbal' | 'data-insights'
  topic: string
  difficulty: 'basic' | 'intermediate' | 'advanced'
}

export interface FlashcardDeck {
  id: string
  name: string
  section: string
  cardCount: number
  cards: Flashcard[]
}

// ── Deck 1: Quant Formulas (25 cards) ──────────────────────

const quantFormulas: Flashcard[] = [
  {
    id: 'qf-01',
    front: 'What is the Percent Change formula?',
    back: '% Change = ((New − Old) / Old) × 100\n\nAlways divide by the ORIGINAL value, not the new one.',
    section: 'quant',
    topic: 'Percent Change',
    difficulty: 'basic',
  },
  {
    id: 'qf-02',
    front: 'Compound Interest formula?',
    back: 'A = P(1 + r/n)^(nt)\n\nP = principal, r = annual rate, n = compounds per year, t = years.\nFor continuous compounding: A = Pe^(rt)',
    section: 'quant',
    topic: 'Compound Interest',
    difficulty: 'intermediate',
  },
  {
    id: 'qf-03',
    front: 'Quadratic Formula — solve ax² + bx + c = 0',
    back: 'x = (−b ± √(b² − 4ac)) / 2a\n\nDiscriminant (b² − 4ac):\n• > 0 → two real roots\n• = 0 → one root\n• < 0 → no real roots',
    section: 'quant',
    topic: 'Quadratic Formula',
    difficulty: 'intermediate',
  },
  {
    id: 'qf-04',
    front: 'Exponent rule: aᵐ × aⁿ = ?',
    back: 'aᵐ × aⁿ = aᵐ⁺ⁿ\n\nSame base → add exponents when multiplying.\naᵐ / aⁿ = aᵐ⁻ⁿ (subtract when dividing).',
    section: 'quant',
    topic: 'Exponent Rules',
    difficulty: 'basic',
  },
  {
    id: 'qf-05',
    front: 'Exponent rule: (aᵐ)ⁿ = ?',
    back: '(aᵐ)ⁿ = aᵐⁿ\n\nPower to a power → multiply exponents.\nAlso: (ab)ⁿ = aⁿbⁿ',
    section: 'quant',
    topic: 'Exponent Rules',
    difficulty: 'basic',
  },
  {
    id: 'qf-06',
    front: 'Combinations formula: nCr = ?',
    back: 'nCr = n! / (r!(n − r)!)\n\nOrder does NOT matter. "Choose r from n."\nExample: 5C2 = 10',
    section: 'quant',
    topic: 'Combinatorics',
    difficulty: 'intermediate',
  },
  {
    id: 'qf-07',
    front: 'Permutations formula: nPr = ?',
    back: 'nPr = n! / (n − r)!\n\nOrder MATTERS. "Arrange r items from n."\nnPr = nCr × r!',
    section: 'quant',
    topic: 'Combinatorics',
    difficulty: 'intermediate',
  },
  {
    id: 'qf-08',
    front: 'Distance, Rate, Time relationship?',
    back: 'Distance = Rate × Time\n\nRearranges to:\n• Rate = Distance / Time\n• Time = Distance / Rate\n\nFor combined rates: add individual rates.',
    section: 'quant',
    topic: 'Word Problems',
    difficulty: 'basic',
  },
  {
    id: 'qf-09',
    front: 'Combined Work Rate formula?',
    back: '1/A + 1/B = 1/T\n\nA and B are individual completion times.\nT = combined time.\nConvert to rates, add, then invert.',
    section: 'quant',
    topic: 'Word Problems',
    difficulty: 'intermediate',
  },
  {
    id: 'qf-10',
    front: 'Probability of A OR B?',
    back: 'P(A or B) = P(A) + P(B) − P(A and B)\n\nInclusion-exclusion: subtract the overlap.\nFor mutually exclusive events: P(A or B) = P(A) + P(B)',
    section: 'quant',
    topic: 'Probability',
    difficulty: 'intermediate',
  },
  {
    id: 'qf-11',
    front: 'Probability of A AND B (independent events)?',
    back: 'P(A and B) = P(A) × P(B)\n\nOnly when events are independent.\nIf dependent, use: P(A and B) = P(A) × P(B|A)',
    section: 'quant',
    topic: 'Probability',
    difficulty: 'intermediate',
  },
  {
    id: 'qf-12',
    front: 'Average (Arithmetic Mean) formula?',
    back: 'Average = Sum of values / Number of values\n\nRearrange: Sum = Average × Count\nUseful for "combined groups" problems.',
    section: 'quant',
    topic: 'Statistics',
    difficulty: 'basic',
  },
  {
    id: 'qf-13',
    front: 'Weighted Average formula?',
    back: 'WA = (w₁x₁ + w₂x₂ + … + wₙxₙ) / (w₁ + w₂ + … + wₙ)\n\nEach value is multiplied by its weight before averaging.',
    section: 'quant',
    topic: 'Statistics',
    difficulty: 'intermediate',
  },
  {
    id: 'qf-14',
    front: 'Difference of Squares factoring?',
    back: 'a² − b² = (a + b)(a − b)\n\nWorks in reverse too:\n97 × 103 = (100 − 3)(100 + 3) = 10000 − 9 = 9991',
    section: 'quant',
    topic: 'Algebra',
    difficulty: 'basic',
  },
  {
    id: 'qf-15',
    front: 'Slope formula between two points?',
    back: 'slope = (y₂ − y₁) / (x₂ − x₁)\n\nParallel lines: same slope.\nPerpendicular lines: slopes are negative reciprocals (m₁ × m₂ = −1).',
    section: 'quant',
    topic: 'Coordinate Geometry',
    difficulty: 'basic',
  },
  {
    id: 'qf-16',
    front: 'Simple Interest formula?',
    back: 'I = P × R × T\n\nP = principal, R = annual interest rate, T = time in years.\nInterest is earned on the principal only (not on accumulated interest).',
    section: 'quant',
    topic: 'Interest',
    difficulty: 'basic',
  },
  {
    id: 'qf-17',
    front: 'Number of factors from prime factorization?',
    back: 'If N = p₁ᵃ × p₂ᵇ × p₃ᶜ\nTotal factors = (a+1)(b+1)(c+1)\n\nExample: 72 = 2³ × 3² → (3+1)(2+1) = 12 factors',
    section: 'quant',
    topic: 'Number Properties',
    difficulty: 'intermediate',
  },
  {
    id: 'qf-18',
    front: 'GCD × LCM relationship?',
    back: 'GCD(a, b) × LCM(a, b) = a × b\n\nFor prime factorization:\n• GCD → take MINIMUM exponent per prime\n• LCM → take MAXIMUM exponent per prime',
    section: 'quant',
    topic: 'Number Properties',
    difficulty: 'intermediate',
  },
  {
    id: 'qf-19',
    front: 'Count of terms in an evenly spaced set?',
    back: 'Count = (Last − First) / Spacing + 1\n\nExample: even numbers from 2 to 100:\n(100 − 2) / 2 + 1 = 50\n\nDon\'t forget the +1!',
    section: 'quant',
    topic: 'Number Properties',
    difficulty: 'basic',
  },
  {
    id: 'qf-20',
    front: 'Average of an evenly spaced set?',
    back: 'Average = (First + Last) / 2\n\nIn an evenly spaced set, the average equals the median.',
    section: 'quant',
    topic: 'Statistics',
    difficulty: 'basic',
  },
  {
    id: 'qf-21',
    front: 'Mixture Problems formula?',
    back: 'C₁V₁ + C₂V₂ = C₃V₃\n\nC = concentration (or price), V = volume (or quantity).\nThe total amount of substance is conserved.',
    section: 'quant',
    topic: 'Word Problems',
    difficulty: 'intermediate',
  },
  {
    id: 'qf-22',
    front: 'What does a⁰ equal?',
    back: 'a⁰ = 1 (for any a ≠ 0)\n\n0⁰ is undefined on the GMAT.\nRemember: a⁻ⁿ = 1/aⁿ',
    section: 'quant',
    topic: 'Exponent Rules',
    difficulty: 'basic',
  },
  {
    id: 'qf-23',
    front: 'Absolute value: |x| = a. What are the solutions?',
    back: 'x = a or x = −a\n\nFor inequalities:\n• |x| < a → −a < x < a\n• |x| > a → x < −a or x > a',
    section: 'quant',
    topic: 'Algebra',
    difficulty: 'intermediate',
  },
  {
    id: 'qf-24',
    front: 'Standard Deviation — what happens when you add a constant to every value?',
    back: 'Adding a constant to every value does NOT change the standard deviation.\n\nMultiplying every value by a constant DOES — it multiplies SD by |constant|.',
    section: 'quant',
    topic: 'Statistics',
    difficulty: 'advanced',
  },
  {
    id: 'qf-25',
    front: 'Profit, Revenue, Cost relationship?',
    back: 'Profit = Revenue − Cost\nMargin = Profit / Revenue\nMarkup = Profit / Cost\n\nMargin is based on revenue; markup is based on cost. Don\'t confuse them!',
    section: 'quant',
    topic: 'Word Problems',
    difficulty: 'basic',
  },
]

// ── Deck 2: Number Properties (20 cards) ───────────────────

const numberProperties: Flashcard[] = [
  {
    id: 'np-01',
    front: 'Is 0 even or odd?',
    back: 'Even. Zero is an even integer.\n\n0 is also neither positive nor negative.',
    section: 'quant',
    topic: 'Number Properties',
    difficulty: 'basic',
  },
  {
    id: 'np-02',
    front: 'Divisibility rule for 8?',
    back: 'Last 3 digits divisible by 8.\n\nExample: 1,024 → 024 = 24. 24 / 8 = 3 ✓',
    section: 'quant',
    topic: 'Divisibility',
    difficulty: 'basic',
  },
  {
    id: 'np-03',
    front: 'Divisibility rule for 3?',
    back: 'Sum of digits is divisible by 3.\n\nExample: 372 → 3 + 7 + 2 = 12. 12 / 3 = 4 ✓',
    section: 'quant',
    topic: 'Divisibility',
    difficulty: 'basic',
  },
  {
    id: 'np-04',
    front: 'Divisibility rule for 9?',
    back: 'Sum of digits is divisible by 9.\n\nExample: 729 → 7 + 2 + 9 = 18. 18 / 9 = 2 ✓',
    section: 'quant',
    topic: 'Divisibility',
    difficulty: 'basic',
  },
  {
    id: 'np-05',
    front: 'Divisibility rule for 4?',
    back: 'Last 2 digits form a number divisible by 4.\n\nExample: 316 → 16. 16 / 4 = 4 ✓',
    section: 'quant',
    topic: 'Divisibility',
    difficulty: 'basic',
  },
  {
    id: 'np-06',
    front: 'Divisibility rule for 6?',
    back: 'Divisible by BOTH 2 AND 3.\n\nCheck: last digit is even AND digit sum divisible by 3.',
    section: 'quant',
    topic: 'Divisibility',
    difficulty: 'basic',
  },
  {
    id: 'np-07',
    front: 'Is 1 a prime number?',
    back: 'No. 1 is NOT prime.\n\nA prime number has exactly 2 distinct positive factors. 1 has only one factor (itself).\n\n2 is the smallest prime and the only even prime.',
    section: 'quant',
    topic: 'Primes',
    difficulty: 'basic',
  },
  {
    id: 'np-08',
    front: 'Even × Odd = ?',
    back: 'Even.\n\nRules:\n• Even × anything = Even\n• Odd × Odd = Odd\n• Even + Even = Even\n• Odd + Odd = Even\n• Even + Odd = Odd',
    section: 'quant',
    topic: 'Even/Odd',
    difficulty: 'basic',
  },
  {
    id: 'np-09',
    front: 'What is the remainder when dividing by 10?',
    back: 'The units digit of the number.\n\n237 / 10 → remainder 7\n\nThis extends: remainder when dividing by 100 = last 2 digits.',
    section: 'quant',
    topic: 'Remainders',
    difficulty: 'basic',
  },
  {
    id: 'np-10',
    front: 'How many prime numbers between 1 and 30?',
    back: '10 primes: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29\n\nMemorize the primes up to 30 — they appear constantly on the GMAT.',
    section: 'quant',
    topic: 'Primes',
    difficulty: 'basic',
  },
  {
    id: 'np-11',
    front: 'What is the units digit pattern for powers of 7?',
    back: '7¹ = 7, 7² = 49, 7³ = 343, 7⁴ = 2401\nPattern: 7, 9, 3, 1 (repeats every 4)\n\nTo find units digit of 7ⁿ: find n mod 4.',
    section: 'quant',
    topic: 'Number Properties',
    difficulty: 'intermediate',
  },
  {
    id: 'np-12',
    front: 'Product of n consecutive integers — what is it always divisible by?',
    back: 'n! (n factorial)\n\nProduct of 3 consecutive integers → always divisible by 6\nProduct of 4 consecutive integers → always divisible by 24',
    section: 'quant',
    topic: 'Number Properties',
    difficulty: 'intermediate',
  },
  {
    id: 'np-13',
    front: 'n(n+1) — what do we know about this product?',
    back: 'Always even.\n\nOne of any two consecutive integers must be even, so their product is always even.',
    section: 'quant',
    topic: 'Number Properties',
    difficulty: 'basic',
  },
  {
    id: 'np-14',
    front: 'How many trailing zeros does 100! have?',
    back: '24 trailing zeros.\n\nCount factors of 5: ⌊100/5⌋ + ⌊100/25⌋ = 20 + 4 = 24\n\nTrailing zeros = min(factors of 2, factors of 5). There are always more 2s.',
    section: 'quant',
    topic: 'Number Properties',
    difficulty: 'advanced',
  },
  {
    id: 'np-15',
    front: 'Remainder formula: Dividend = ?',
    back: 'Dividend = Quotient × Divisor + Remainder\n\nExample: 17 = 3 × 5 + 2\nSo 17 ÷ 5 has quotient 3, remainder 2.',
    section: 'quant',
    topic: 'Remainders',
    difficulty: 'basic',
  },
  {
    id: 'np-16',
    front: 'If a number is divisible by 12, what must it also be divisible by?',
    back: '1, 2, 3, 4, 6, and 12.\n\nAll factors of 12 are factors of any multiple of 12.\n12 = 2² × 3, so any combination of these prime factors divides it.',
    section: 'quant',
    topic: 'Divisibility',
    difficulty: 'intermediate',
  },
  {
    id: 'np-17',
    front: 'Negative × Negative = ?',
    back: 'Positive.\n\nSign rules for multiplication:\n• (+)(+) = +\n• (−)(−) = +\n• (+)(−) = −\n• (−)(+) = −',
    section: 'quant',
    topic: 'Number Properties',
    difficulty: 'basic',
  },
  {
    id: 'np-18',
    front: 'What happens when you square a fraction between 0 and 1?',
    back: 'The result is SMALLER than the original.\n\nExample: (1/2)² = 1/4 < 1/2\n\nConversely, taking the square root of a fraction between 0 and 1 gives a LARGER number.',
    section: 'quant',
    topic: 'Number Properties',
    difficulty: 'intermediate',
  },
  {
    id: 'np-19',
    front: 'Sum of first n positive integers?',
    back: 'Sum = n(n + 1) / 2\n\nExample: sum of 1 to 100 = 100 × 101 / 2 = 5,050',
    section: 'quant',
    topic: 'Number Properties',
    difficulty: 'intermediate',
  },
  {
    id: 'np-20',
    front: 'A perfect square has an ___ number of factors.',
    back: 'Odd number of factors.\n\nEvery factor pairs up (d × N/d), except the square root which pairs with itself.\n\nExample: 36 has factors 1,2,3,4,6,9,12,18,36 → 9 factors (odd).',
    section: 'quant',
    topic: 'Number Properties',
    difficulty: 'intermediate',
  },
]

// ── Deck 3: Critical Reasoning Patterns (20 cards) ─────────

const criticalReasoning: Flashcard[] = [
  {
    id: 'cr-01',
    front: 'What does a Strengthen question ask?',
    back: 'Find the answer that makes the conclusion MORE likely by bridging the gap between premise and conclusion.\n\nLook for: "Which of the following, if true, most strengthens the argument?"',
    section: 'verbal',
    topic: 'Strengthen',
    difficulty: 'basic',
  },
  {
    id: 'cr-02',
    front: 'What does a Weaken question ask?',
    back: 'Find the answer that makes the conclusion LESS likely.\n\nThe correct answer introduces new information that widens the logical gap between premise and conclusion.',
    section: 'verbal',
    topic: 'Weaken',
    difficulty: 'basic',
  },
  {
    id: 'cr-03',
    front: 'How to identify an assumption?',
    back: 'Use the Negation Test: negate the answer choice — if the argument falls apart, it\'s the assumption.\n\nAn assumption is an unstated premise that MUST be true for the conclusion to hold.',
    section: 'verbal',
    topic: 'Assumption',
    difficulty: 'intermediate',
  },
  {
    id: 'cr-04',
    front: 'What is the structure of every CR argument?',
    back: 'Premise → [Gap] → Conclusion\n\nPremises = facts given as true\nConclusion = the claim being made\nGap = the unstated logical link',
    section: 'verbal',
    topic: 'Argument Structure',
    difficulty: 'basic',
  },
  {
    id: 'cr-05',
    front: 'How to spot a "Correlation ≠ Causation" flaw?',
    back: 'The argument observes that A and B occur together and concludes A causes B.\n\nCounter: Maybe B causes A, a third factor C causes both, or it\'s coincidence.',
    section: 'verbal',
    topic: 'Logical Flaws',
    difficulty: 'intermediate',
  },
  {
    id: 'cr-06',
    front: 'What is a Scope Shift flaw?',
    back: 'The conclusion uses different terms/scope than the premise.\n\nExample: Premise discusses "sales employees" but conclusion is about "all employees."\n\nWatch for subtle changes in who/what is being discussed.',
    section: 'verbal',
    topic: 'Logical Flaws',
    difficulty: 'intermediate',
  },
  {
    id: 'cr-07',
    front: 'What is an "Evaluate the Argument" question asking?',
    back: 'Identify information that would help determine whether the conclusion is valid.\n\nThe correct answer, if answered YES, strengthens; if answered NO, weakens (or vice versa).',
    section: 'verbal',
    topic: 'Evaluate',
    difficulty: 'intermediate',
  },
  {
    id: 'cr-08',
    front: 'What is a Paradox/Discrepancy question?',
    back: 'Two facts seem to contradict each other. Find the answer that explains how BOTH can be true.\n\nDon\'t pick answers that only explain one side — you need to resolve the tension.',
    section: 'verbal',
    topic: 'Paradox',
    difficulty: 'intermediate',
  },
  {
    id: 'cr-09',
    front: 'What is a "Boldface" question?',
    back: 'Identifies the ROLE of bolded statements in the argument.\n\nCommon roles: main conclusion, supporting premise, counter-premise, objection, evidence.\n\nDon\'t evaluate truth — evaluate function.',
    section: 'verbal',
    topic: 'Argument Structure',
    difficulty: 'advanced',
  },
  {
    id: 'cr-10',
    front: 'Red flag: answer choice says "proves" or "guarantees"',
    back: 'Almost always wrong for Strengthen questions.\n\nStrengthening makes the conclusion MORE likely — it doesn\'t need to prove it definitively.\n\nExtreme language = usually wrong.',
    section: 'verbal',
    topic: 'Strategy',
    difficulty: 'intermediate',
  },
  {
    id: 'cr-11',
    front: 'What does an Inference/Must Be True question ask?',
    back: 'Find what must be true based ONLY on the given information.\n\nStay close to the text. The correct answer follows logically — don\'t bring in outside knowledge.',
    section: 'verbal',
    topic: 'Inference',
    difficulty: 'basic',
  },
  {
    id: 'cr-12',
    front: 'How do you handle "EXCEPT" in CR questions?',
    back: 'Four answers DO what the question asks; one does NOT.\n\nStrategy: test each answer. Mark it as YES (does the thing) or NO (doesn\'t). The NO answer is correct.',
    section: 'verbal',
    topic: 'Strategy',
    difficulty: 'basic',
  },
  {
    id: 'cr-13',
    front: 'What is a "Flaw in Reasoning" question?',
    back: 'Identify the logical error in the argument.\n\nCommon flaws:\n• Correlation → Causation\n• Scope shift\n• Sampling bias\n• Part-to-whole generalization\n• Appeal to authority',
    section: 'verbal',
    topic: 'Logical Flaws',
    difficulty: 'intermediate',
  },
  {
    id: 'cr-14',
    front: 'Trap answer: "Out of scope" — what does this mean?',
    back: 'The answer introduces a topic or comparison not discussed in the argument.\n\nIf the argument is about Company X\'s profits, an answer about Company Y\'s market share is out of scope.',
    section: 'verbal',
    topic: 'Strategy',
    difficulty: 'basic',
  },
  {
    id: 'cr-15',
    front: 'How do you identify the conclusion of a CR passage?',
    back: 'Look for conclusion indicators:\n• Therefore, thus, hence, so\n• Consequently, as a result\n• This suggests/indicates/shows\n\nThe conclusion is what the author is trying to PROVE, not what they assume.',
    section: 'verbal',
    topic: 'Argument Structure',
    difficulty: 'basic',
  },
  {
    id: 'cr-16',
    front: 'What is the "Absence of Evidence" flaw?',
    back: '"Absence of evidence is NOT evidence of absence."\n\nJust because something hasn\'t been proven doesn\'t mean it\'s false. Watch for arguments that say "no evidence of X, therefore X doesn\'t exist."',
    section: 'verbal',
    topic: 'Logical Flaws',
    difficulty: 'intermediate',
  },
  {
    id: 'cr-17',
    front: 'Plan/Proposal questions — what\'s the strategy?',
    back: 'The argument proposes a plan to achieve a goal.\n\nWeaken: show the plan won\'t achieve the goal, or has a fatal flaw.\nStrengthen: show the plan addresses a potential objection.\nAssumption: the plan has no fatal unaddressed flaw.',
    section: 'verbal',
    topic: 'Strategy',
    difficulty: 'intermediate',
  },
  {
    id: 'cr-18',
    front: 'What is "Necessary vs. Sufficient" in CR?',
    back: 'Necessary: must be true for the conclusion (but alone may not be enough).\nSufficient: alone guarantees the conclusion (but may not be required).\n\nAssumption questions ask for necessary conditions, not sufficient ones.',
    section: 'verbal',
    topic: 'Assumption',
    difficulty: 'advanced',
  },
  {
    id: 'cr-19',
    front: 'Sampling Bias flaw — what to look for?',
    back: 'The argument draws conclusions about a large group based on a non-representative sample.\n\nExample: surveying only gym members and concluding "most people exercise regularly."',
    section: 'verbal',
    topic: 'Logical Flaws',
    difficulty: 'intermediate',
  },
  {
    id: 'cr-20',
    front: 'RC vs CR: How do Inference questions differ?',
    back: 'RC Inference: what can be inferred from the passage (close to text).\nCR Inference: what must be true based on the given statements.\n\nBoth require staying within the given information — no outside knowledge.',
    section: 'verbal',
    topic: 'Strategy',
    difficulty: 'advanced',
  },
]

// ── Deck 4: Data Sufficiency Framework (20 cards) ──────────

const dataSufficiency: Flashcard[] = [
  {
    id: 'ds-01',
    front: 'What are the 5 DS answer choices?',
    back: '(A) Statement 1 ALONE is sufficient, but Statement 2 alone is not\n(B) Statement 2 ALONE is sufficient, but Statement 1 alone is not\n(C) BOTH statements TOGETHER are sufficient, but NEITHER alone is sufficient\n(D) EACH statement ALONE is sufficient\n(E) Statements 1 and 2 TOGETHER are NOT sufficient',
    section: 'data-insights',
    topic: 'DS Framework',
    difficulty: 'basic',
  },
  {
    id: 'ds-02',
    front: 'What is DS Answer Choice C?',
    back: 'BOTH statements TOGETHER are sufficient, but NEITHER alone is sufficient.\n\nYou can only pick C after confirming each statement is insufficient on its own.',
    section: 'data-insights',
    topic: 'DS Framework',
    difficulty: 'basic',
  },
  {
    id: 'ds-03',
    front: 'When do you pick E in Data Sufficiency?',
    back: 'When even BOTH statements together don\'t provide enough information to answer the question.\n\nMake sure you\'ve truly combined both — don\'t give up too early.',
    section: 'data-insights',
    topic: 'DS Framework',
    difficulty: 'basic',
  },
  {
    id: 'ds-04',
    front: 'DS Decision Tree — Step 1?',
    back: 'Test Statement 1 ALONE.\n\nCan you get a definitive answer? If YES → S1 is sufficient. If NO → S1 is insufficient.\n\nNever look at Statement 2 during this step.',
    section: 'data-insights',
    topic: 'DS Framework',
    difficulty: 'basic',
  },
  {
    id: 'ds-05',
    front: 'DS golden rule: Sufficiency ≠ ?',
    back: 'Sufficiency ≠ Solving.\n\nYou do NOT need to calculate the actual answer. You only need to determine whether a UNIQUE answer EXISTS.\n\nStop as soon as you know. Save time.',
    section: 'data-insights',
    topic: 'DS Strategy',
    difficulty: 'intermediate',
  },
  {
    id: 'ds-06',
    front: '"Is x positive?" — Statement: x² = 9. Sufficient?',
    back: 'NOT sufficient.\n\nx² = 9 → x = 3 or x = −3.\nWe get two possible values, so we can\'t determine if x is positive. Need more info.',
    section: 'data-insights',
    topic: 'DS Practice',
    difficulty: 'intermediate',
  },
  {
    id: 'ds-07',
    front: 'In DS, what does "sufficient" mean?',
    back: 'The statement provides enough information to answer the question with a SINGLE, DEFINITIVE answer.\n\nFor Yes/No questions: sufficient means we can definitively say YES or definitively say NO.',
    section: 'data-insights',
    topic: 'DS Framework',
    difficulty: 'basic',
  },
  {
    id: 'ds-08',
    front: 'DS trap: getting a definitive NO. Is that sufficient?',
    back: 'YES! A definitive NO is still sufficient.\n\nExample: "Is x > 5?" If statement tells us x = 3, the answer is "No" — and that\'s sufficient because we know for certain.',
    section: 'data-insights',
    topic: 'DS Strategy',
    difficulty: 'intermediate',
  },
  {
    id: 'ds-09',
    front: 'In DS, can the two statements contradict each other?',
    back: 'NEVER. Statements are always true and always consistent with each other.\n\nIf you think they contradict, you\'ve made an error. Recheck your work.',
    section: 'data-insights',
    topic: 'DS Framework',
    difficulty: 'intermediate',
  },
  {
    id: 'ds-10',
    front: 'DS number plugging strategy — how many values to test?',
    back: 'Test at least 2-3 different values that satisfy the statement.\n\nIf you get different answers for different valid values → insufficient.\nIf every valid value gives the same answer → likely sufficient (but prove it).',
    section: 'data-insights',
    topic: 'DS Strategy',
    difficulty: 'intermediate',
  },
  {
    id: 'ds-11',
    front: 'DS: "What is the value of x?" — how many solutions needed for sufficiency?',
    back: 'Exactly ONE unique value.\n\nIf a statement gives x = 5 → sufficient.\nIf a statement gives x = 5 or x = −5 → NOT sufficient (two possible values).',
    section: 'data-insights',
    topic: 'DS Framework',
    difficulty: 'basic',
  },
  {
    id: 'ds-12',
    front: 'DS answer choice D — when to pick it?',
    back: 'When EACH statement ALONE is sufficient.\n\nS1 alone → sufficient\nS2 alone → sufficient\nAnswer: D\n\nYou don\'t need to combine them.',
    section: 'data-insights',
    topic: 'DS Framework',
    difficulty: 'basic',
  },
  {
    id: 'ds-13',
    front: 'Common DS trap with inequalities — what to watch for?',
    back: 'Don\'t assume variables are positive or integers unless stated.\n\nTest: positive, negative, zero, fractions, large/small values.\n\nExample: x² > x doesn\'t mean x > 1 (what about x = −5?).',
    section: 'data-insights',
    topic: 'DS Strategy',
    difficulty: 'advanced',
  },
  {
    id: 'ds-14',
    front: 'DS: geometric questions — what info determines a unique shape?',
    back: 'Circle: just the radius\nRectangle: both length and width (or area + one side)\nTriangle: all 3 sides (SSS), or 2 sides + included angle (SAS)\n\nKnow what uniquely defines each shape.',
    section: 'data-insights',
    topic: 'DS Practice',
    difficulty: 'intermediate',
  },
  {
    id: 'ds-15',
    front: 'How to handle DS with remainders?',
    back: 'List actual numbers that satisfy the remainder condition.\n\n"x divided by 5 has remainder 2" → x could be 2, 7, 12, 17, 22…\n\nThen test whether these all give the same answer to the question.',
    section: 'data-insights',
    topic: 'DS Practice',
    difficulty: 'intermediate',
  },
  {
    id: 'ds-16',
    front: 'DS time management — how long per question?',
    back: 'Target: ~2 minutes per DS question.\n\nIf stuck after 2.5 minutes, make your best guess and move on.\nDS rewards structured thinking over calculation.',
    section: 'data-insights',
    topic: 'DS Strategy',
    difficulty: 'basic',
  },
  {
    id: 'ds-17',
    front: 'DS: can Statement 2 repeat information from Statement 1?',
    back: 'Statements can overlap in information, but they\'re always tested independently first.\n\nEven if they seem similar, evaluate each separately before combining.',
    section: 'data-insights',
    topic: 'DS Framework',
    difficulty: 'intermediate',
  },
  {
    id: 'ds-18',
    front: '"Is x an integer?" — Statement: x² is an integer. Sufficient?',
    back: 'NOT sufficient.\n\nx = √2 → x² = 2 (integer), but x is NOT an integer.\nx = 3 → x² = 9 (integer), and x IS an integer.\n\nDifferent outcomes → insufficient.',
    section: 'data-insights',
    topic: 'DS Practice',
    difficulty: 'advanced',
  },
  {
    id: 'ds-19',
    front: 'When both statements give the SAME info, the answer is NOT C. Why?',
    back: 'If both statements give identical information, combining them adds nothing new.\n\nIf each alone is insufficient and together they\'re still the same info → answer is E, not C.',
    section: 'data-insights',
    topic: 'DS Strategy',
    difficulty: 'advanced',
  },
  {
    id: 'ds-20',
    front: 'DS flow: S1 sufficient, S2 sufficient → answer?',
    back: 'Answer: D (Each statement ALONE is sufficient).\n\nDS flow:\n• S1 suff + S2 suff → D\n• S1 suff + S2 not → A\n• S1 not + S2 suff → B\n• Neither alone → combine → suff? C : E',
    section: 'data-insights',
    topic: 'DS Framework',
    difficulty: 'basic',
  },
]

// ── Deck 5: GMAT Vocabulary & Concepts (15 cards) ──────────

const vocabConcepts: Flashcard[] = [
  {
    id: 'vc-01',
    front: 'What is a weighted average?',
    back: 'An average where each value is multiplied by its weight (importance) before summing, then divided by the total weight.\n\nUsed when groups have different sizes or different importance levels.',
    section: 'quant',
    topic: 'Concepts',
    difficulty: 'basic',
  },
  {
    id: 'vc-02',
    front: 'What does "inclusive" mean in counting problems?',
    back: 'Both endpoints are included.\n\n"Integers from 3 to 7 inclusive" = {3, 4, 5, 6, 7} = 5 numbers.\nFormula: Last − First + 1',
    section: 'quant',
    topic: 'Concepts',
    difficulty: 'basic',
  },
  {
    id: 'vc-03',
    front: 'What is the median?',
    back: 'The middle value when data is sorted.\n\nOdd count: the middle number.\nEven count: average of the two middle numbers.\n\nMedian is less affected by outliers than the mean.',
    section: 'quant',
    topic: 'Concepts',
    difficulty: 'basic',
  },
  {
    id: 'vc-04',
    front: 'What is a "rate" on the GMAT?',
    back: 'A ratio that compares two different units.\n\nExamples:\n• Speed: miles per hour\n• Work rate: jobs per hour (1/time to complete)\n• Price rate: cost per item',
    section: 'quant',
    topic: 'Concepts',
    difficulty: 'basic',
  },
  {
    id: 'vc-05',
    front: 'What is "standard deviation" intuitively?',
    back: 'A measure of how spread out values are from the mean.\n\n• Small SD → values clustered near the mean\n• Large SD → values spread out widely\n• SD = 0 → all values are identical',
    section: 'quant',
    topic: 'Concepts',
    difficulty: 'intermediate',
  },
  {
    id: 'vc-06',
    front: 'What does "mutually exclusive" mean?',
    back: 'Two events that CANNOT happen at the same time.\n\nP(A and B) = 0\nP(A or B) = P(A) + P(B)\n\nExample: rolling a 3 and rolling a 5 on one die.',
    section: 'quant',
    topic: 'Concepts',
    difficulty: 'intermediate',
  },
  {
    id: 'vc-07',
    front: 'What is a "factor" vs. a "multiple"?',
    back: 'Factor: divides evenly into the number.\n• Factors of 12: 1, 2, 3, 4, 6, 12\n\nMultiple: the number divides evenly into it.\n• Multiples of 12: 12, 24, 36, 48…\n\n"Factors are Few, Multiples are Many"',
    section: 'quant',
    topic: 'Concepts',
    difficulty: 'basic',
  },
  {
    id: 'vc-08',
    front: 'What is an "integer"?',
    back: 'A whole number (positive, negative, or zero).\n\n…, −3, −2, −1, 0, 1, 2, 3, …\n\nNOT integers: fractions, decimals, irrational numbers (π, √2).',
    section: 'quant',
    topic: 'Concepts',
    difficulty: 'basic',
  },
  {
    id: 'vc-09',
    front: 'What is "Data Insights" on GMAT Focus Edition?',
    back: 'The third section of GMAT Focus Edition, combining:\n• Data Sufficiency\n• Multi-Source Reasoning\n• Table Analysis\n• Graphics Interpretation\n• Two-Part Analysis\n\n21 questions in 45 minutes.',
    section: 'data-insights',
    topic: 'Concepts',
    difficulty: 'basic',
  },
  {
    id: 'vc-10',
    front: 'GMAT Focus Edition — what are the 3 sections?',
    back: '1. Quantitative Reasoning (21 Qs, 45 min)\n2. Verbal Reasoning (23 Qs, 45 min)\n3. Data Insights (21 Qs, 45 min)\n\nTotal: 2 hours 15 minutes + breaks.\nScore range: 205–805.',
    section: 'data-insights',
    topic: 'Concepts',
    difficulty: 'basic',
  },
  {
    id: 'vc-11',
    front: 'What does "perpendicular" mean?',
    back: 'Two lines that meet at a 90° right angle.\n\nPerpendicular slopes are negative reciprocals:\nIf line 1 has slope m, line 2 has slope −1/m.\n\nm × (−1/m) = −1',
    section: 'quant',
    topic: 'Concepts',
    difficulty: 'basic',
  },
  {
    id: 'vc-12',
    front: 'What is "number sense" and why does it matter?',
    back: 'The intuitive understanding of how numbers behave.\n\nExamples:\n• Multiplying by 0.5 = dividing by 2\n• Adding negative = subtracting\n• Squaring a negative = positive\n\nHelps catch errors and estimate quickly.',
    section: 'quant',
    topic: 'Concepts',
    difficulty: 'basic',
  },
  {
    id: 'vc-13',
    front: 'What is an "overlapping sets" problem?',
    back: 'Items belong to two or more categories simultaneously.\n\nUse the formula:\nTotal = A + B − Both + Neither\n\nOr use a Venn diagram / matrix to organize.',
    section: 'quant',
    topic: 'Concepts',
    difficulty: 'intermediate',
  },
  {
    id: 'vc-14',
    front: 'What does "at least one" mean in probability?',
    back: 'P(at least one) = 1 − P(none)\n\nThe complement approach is almost always easier than counting each case.\n\nExample: P(at least one head in 3 flips) = 1 − (1/2)³ = 7/8',
    section: 'quant',
    topic: 'Concepts',
    difficulty: 'intermediate',
  },
  {
    id: 'vc-15',
    front: 'What is "backsolving" on the GMAT?',
    back: 'Plugging answer choices back into the problem to see which one works.\n\nStart with answer choice C (middle value). If too big, go smaller; if too small, go bigger.\n\nBest for: integer answers, "what is the value of x" problems.',
    section: 'quant',
    topic: 'Strategy',
    difficulty: 'intermediate',
  },
]

// ── Build Decks ────────────────────────────────────────────

export const FLASHCARD_DECKS: FlashcardDeck[] = [
  {
    id: 'quant-formulas',
    name: 'Quant Formulas',
    section: 'quant',
    cardCount: quantFormulas.length,
    cards: quantFormulas,
  },
  {
    id: 'number-properties',
    name: 'Number Properties',
    section: 'quant',
    cardCount: numberProperties.length,
    cards: numberProperties,
  },
  {
    id: 'critical-reasoning',
    name: 'Critical Reasoning Patterns',
    section: 'verbal',
    cardCount: criticalReasoning.length,
    cards: criticalReasoning,
  },
  {
    id: 'data-sufficiency',
    name: 'Data Sufficiency Framework',
    section: 'data-insights',
    cardCount: dataSufficiency.length,
    cards: dataSufficiency,
  },
  {
    id: 'vocab-concepts',
    name: 'GMAT Vocabulary & Concepts',
    section: 'quant',
    cardCount: vocabConcepts.length,
    cards: vocabConcepts,
  },
]

export function getDeckById(id: string): FlashcardDeck | undefined {
  return FLASHCARD_DECKS.find(d => d.id === id)
}

export function getAllCards(): Flashcard[] {
  return FLASHCARD_DECKS.flatMap(d => d.cards)
}
